version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py migrate && 
      python manage.py init_admin &&
      python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=p455WORDC#
      - DB_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=p455WORDC#
      - DJANGO_SUPERUSER_USERNAME=django_admin
      - DJANGO_SUPERUSER_EMAIL=django_admin@gmail.com
      - DJANGO_SECRET_KEY=rnf554@8_nd(99o)s3d(q)lg3dgi5@jp=hn&8(dwrp-ya+09&i
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p455WORDC#